language: python
python: 3.6
env:
- TOXENV=py3
- TOXENV=flake8
install:
- pip install tox
script: tox

jobs:
  include:
  - stage: deploy
    script: echo "Deploying on PyPi ..."
    env:
    install:
    deploy:
      provider: pypi
      user: JosefFriedrich
      password:
        secure: "Dvf4ywFWbEmx0OhzaQA0mZlCZ6HpkwqgoTDJ5TBxi4/zkz5sJ7sUWHXd5uCR2OpUUtMBPKzh1f9R5FRCEFFmPHr9oupsEbLaeWx7yux0QmXp/hd2rwO1B44PQwrmNiEQ/n1Ul+zm4JiXJSw9OJDdu5HAgbvjKBLo+tSU4kP24jvVtdklpOnWEUonKbhpuE0BD9M680Xg1NN1FUzIVhcDO4ap6hIZPomHKBYONutLajI6UNGnUslHWwiBL4EXCgIaaocwQi+ohL9rH1H4WeCe9v31vfYhhLT7IHZdvphD04jQYiMr+2Elsdt6uS6FW4/AXbgbAxhS8e4zpklVtcOOBU2zum0D7oSJlkuV0y3ND6jkDFcacywgOlxjIDzE1WKs1dpJxlA57slT8t67hjb83Ax4IFjw8ULLi2qQ3YQVFCUcawWB8AaJA3zT35jukWEH6Mvyzq0spqQmkZavMMl0djp3eFXkpmpayoN5m+IIsNR+a4O50kmnCrJ1RDn5Nq0b+VHaFh1fEMFvkO9jGrd6TZchRyeQceWyNDDJqP9NQ5Lz5Ij3DudpS+UdSDzM8CGhEqjJdC71aUUis6IBi09e3+QCnV1cfLVshmduJ5usjL7A0LMjdoc8D6/Mu7Nq5+FqmVPxew0f967KIrIdbp6bry4A7e5ONgydQlh4rOfkXCc="
      on:
        tags: true
